### ISSUE TITLE
Add header

### ISSUE THREAD

**Issue by Kenrou7** [KenrouIt/cheddar-ecosystem#31]
Add header. Don't make it too big. Make sure to include the 4 links. Make sure it isn't necessary to scroll

![Image](https://github.com/KenrouIt/cheddar-ecosystem/assets/126727722/e3230631-3b13-4f90-bafd-fe549287b98d)

**Comment by Mart-Dan-Rossi** [comment]
Done in branch: add-header

**Comment by Kenrou7** [comment]
Talked to Blaze regarding the scroll. He decided to put a thin purple header with only the social media icons and their corresponding links, without the words.
